-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 09:57:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hardrockstudio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hardrockstudio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hardrockstudio` DEFAULT CHARACTER SET utf8 ;
USE `hardrockstudio` ;

-- -----------------------------------------------------
-- Table `hardrockstudio`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hardrockstudio`.`Customer` (
  `Customer_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Gender` CHAR(1) NULL,
  `Date_Of_Birth` DATE NULL,
  `Phone_Number` VARCHAR(45) NULL,
  `Address_Line_1` VARCHAR(80) NULL,
  `Address_Line_2` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Province` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Zip_Code` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hardrockstudio`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hardrockstudio`.`Genre` (
  `Genre_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Genre_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hardrockstudio`.`Singer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hardrockstudio`.`Singer` (
  `Singer_ID` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Date_Of_Birth` DATE NULL,
  `Gender` CHAR(1) NULL,
  `Last_Album_Released_Date` DATE NULL,
  PRIMARY KEY (`Singer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hardrockstudio`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hardrockstudio`.`Album` (
  `Album_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Genre_ID` INT NOT NULL,
  `Singer_ID` INT NOT NULL,
  `Description` VARCHAR(100) NULL,
  `Released_Date` DATE NULL,
  `Length` DECIMAL(10,2) NULL,
  `Quantity` INT NULL,
  `List_Price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Album_ID`),
  INDEX `FK_Albums_Genre_ID_idx` (`Genre_ID` ASC) VISIBLE,
  INDEX `FK_Albums_Singer_ID_idx` (`Singer_ID` ASC) VISIBLE,
  CONSTRAINT `FK_Albums_Genre_ID`
    FOREIGN KEY (`Genre_ID`)
    REFERENCES `hardrockstudio`.`Genre` (`Genre_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Albums_Singer_ID`
    FOREIGN KEY (`Singer_ID`)
    REFERENCES `hardrockstudio`.`Singer` (`Singer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hardrockstudio`.`Payment_Method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hardrockstudio`.`Payment_Method` (
  `Payment_Method_ID` INT NOT NULL AUTO_INCREMENT,
  `Payment_Method_Desc` VARCHAR(45) NULL,
  PRIMARY KEY (`Payment_Method_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hardrockstudio`.`Billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hardrockstudio`.`Billing` (
  `Billing_ID` INT NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT NOT NULL,
  `Album_ID` INT NOT NULL,
  `Payment_Method_ID` INT NULL,
  `Invoice_ID` INT NULL,
  `Billing_Date` DATE NULL,
  `Units_Sold` INT NULL,
  `Per_Unit_Amount` DECIMAL(10,2) NULL,
  `Ship_Amount` DECIMAL(10,2) NULL,
  `Tax_Amount` DECIMAL(10,2) NULL,
  `Discount_Percent` DECIMAL(10,2) NULL,
  `Total_Billing_Amount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Billing_ID`),
  INDEX `FK_Billing_Customer_ID_idx` (`Customer_ID` ASC) VISIBLE,
  INDEX `FK_Billing_Album_ID_idx` (`Album_ID` ASC) VISIBLE,
  INDEX `FK_Billing_Payment_Method_ID_idx` (`Payment_Method_ID` ASC) VISIBLE,
  CONSTRAINT `FK_Billing_Customer_ID`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `hardrockstudio`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Billing_Album_ID`
    FOREIGN KEY (`Album_ID`)
    REFERENCES `hardrockstudio`.`Album` (`Album_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Billing_Payment_Method_ID`
    FOREIGN KEY (`Payment_Method_ID`)
    REFERENCES `hardrockstudio`.`Payment_Method` (`Payment_Method_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
